import type { CSSProperties } from "react";

export const styles: Record<string, CSSProperties> = {
  page: {
    minHeight: "100vh",
    background: "#f7f8fb",
    color: "#172033",
    fontFamily: "Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, Segoe UI, sans-serif",
  },
  shell: {
    width: "min(1120px, calc(100% - 32px))",
    margin: "0 auto",
    padding: "40px 0",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    gap: 24,
    alignItems: "flex-start",
    marginBottom: 22,
    flexWrap: "wrap",
  },
  eyebrow: {
    margin: "0 0 8px",
    color: "#516079",
    fontSize: 13,
    fontWeight: 700,
    letterSpacing: 0,
    textTransform: "uppercase",
  },
  title: {
    margin: 0,
    fontSize: "clamp(36px, 6vw, 60px)",
    lineHeight: 1,
  },
  subtitle: {
    maxWidth: 640,
    margin: "14px 0 0",
    color: "#5d6b82",
    fontSize: 17,
    lineHeight: 1.6,
  },
  statusGrid: {
    display: "grid",
    gap: 10,
    minWidth: 240,
  },
  statusCard: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: 14,
    border: "1px solid #d9e0ea",
    borderRadius: 8,
    background: "#ffffff",
    boxShadow: "0 10px 26px rgba(23, 32, 51, 0.07)",
  },
  chainBand: {
    marginBottom: 24,
    padding: 20,
    border: "1px solid #dfe5ee",
    borderRadius: 8,
    background: "#ffffff",
    boxShadow: "0 16px 40px rgba(23, 32, 51, 0.08)",
  },
  chainBandTitle: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    marginBottom: 16,
  },
  chainStats: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(130px, 1fr))",
    gap: 12,
  },
  metric: {
    minHeight: 78,
    display: "grid",
    alignContent: "center",
    gap: 8,
    padding: "12px 14px",
    border: "1px solid #dfe5ee",
    borderRadius: 8,
    background: "#fbfcfe",
  },
  wideMetric: {
    minHeight: 78,
    display: "grid",
    alignContent: "center",
    gap: 8,
    padding: "12px 14px",
    border: "1px solid #dfe5ee",
    borderRadius: 8,
    background: "#eef3f7",
    gridColumn: "1 / -1",
  },
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(min(100%, 340px), 1fr))",
    gap: 24,
    alignItems: "start",
  },
  panel: {
    background: "#ffffff",
    border: "1px solid #dfe5ee",
    borderRadius: 8,
    padding: 22,
    boxShadow: "0 16px 40px rgba(23, 32, 51, 0.08)",
  },
  panelTitle: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    marginBottom: 20,
  },
  label: {
    display: "grid",
    gap: 8,
    marginBottom: 16,
    color: "#344055",
    fontSize: 14,
    fontWeight: 700,
  },
  input: {
    width: "100%",
    boxSizing: "border-box",
    border: "1px solid #cfd7e3",
    borderRadius: 8,
    padding: "12px 14px",
    color: "#172033",
    font: "inherit",
    outline: "none",
  },
  textarea: {
    resize: "vertical",
    minHeight: 150,
    lineHeight: 1.5,
  },
  button: {
    width: "100%",
    border: 0,
    borderRadius: 8,
    padding: "13px 16px",
    display: "inline-flex",
    justifyContent: "center",
    alignItems: "center",
    gap: 8,
    background: "#1f7a6b",
    color: "#ffffff",
    font: "inherit",
    fontWeight: 800,
    cursor: "pointer",
  },
  error: {
    margin: "0 0 14px",
    color: "#b42318",
    fontWeight: 700,
  },
  emptyState: {
    padding: 28,
    border: "1px dashed #cfd7e3",
    borderRadius: 8,
    color: "#66758d",
    textAlign: "center",
  },
  blockList: {
    display: "grid",
    gap: 14,
  },
  blockCard: {
    border: "1px solid #dfe5ee",
    borderRadius: 8,
    padding: 16,
    background: "#fbfcfe",
  },
  blockTopline: {
    display: "flex",
    justifyContent: "space-between",
    gap: 12,
    color: "#66758d",
    fontSize: 13,
    flexWrap: "wrap",
  },
  blockIndex: {
    color: "#1f7a6b",
    fontWeight: 800,
  },
  note: {
    margin: "12px 0 8px",
    fontSize: 16,
    lineHeight: 1.6,
  },
  author: {
    margin: "0 0 14px",
    color: "#66758d",
    fontSize: 14,
  },
  anchorSummary: {
    display: "flex",
    justifyContent: "space-between",
    gap: 10,
    marginBottom: 10,
    color: "#344055",
    fontSize: 13,
    fontWeight: 700,
    flexWrap: "wrap",
  },
  hashRows: {
    display: "grid",
    gap: 8,
  },
  hashRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    padding: "9px 10px",
    borderRadius: 8,
    background: "#eef3f7",
    color: "#445169",
    fontSize: 13,
    flexWrap: "wrap",
  },
  hashLabel: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    fontWeight: 700,
  },
};
