create table if not exists public.note_blocks (
  id bigint generated by default as identity primary key,
  block_index integer not null unique,
  timestamp timestamptz not null,
  note jsonb not null,
  previous_hash text not null,
  hash text not null unique,
  anchor jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists note_blocks_block_index_idx
  on public.note_blocks (block_index);
