create table if not exists public.notes (
  id bigint generated by default as identity primary key,
  author text not null default 'anonymous',
  title text not null default '',
  tag text not null default 'General',
  content text not null,
  created_at timestamptz not null default now(),
  deleted_at timestamptz
);

alter table public.notes
  add column if not exists title text not null default '';

alter table public.notes
  add column if not exists tag text not null default 'General';

alter table public.notes
  add column if not exists deleted_at timestamptz;

create index if not exists notes_created_at_idx
  on public.notes (created_at);

create index if not exists notes_tag_idx
  on public.notes (tag);

create index if not exists notes_active_created_at_idx
  on public.notes (created_at)
  where deleted_at is null;

create index if not exists notes_deleted_at_idx
  on public.notes (deleted_at)
  where deleted_at is not null;

do $$
declare
  note_record record;
  parsed_content jsonb;
begin
  for note_record in select id, content from public.notes loop
    begin
      parsed_content := note_record.content::jsonb;

      if jsonb_typeof(parsed_content) = 'object' and parsed_content ? 'content' then
        update public.notes
        set
          title = coalesce(nullif(parsed_content->>'title', ''), title),
          tag = coalesce(nullif(parsed_content->>'tag', ''), tag),
          content = coalesce(nullif(parsed_content->>'content', ''), content)
        where id = note_record.id;
      end if;
    exception when others then
      null;
    end;
  end loop;
end $$;
